# Generated by Django 2.1.dev20180328172503 on 2018-03-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_duration_mins',
            field=models.IntegerField(default=0),
        ),
    ]
