# Generated by Django 2.0.3 on 2018-04-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test_sectionid',
            new_name='test_sectionsid',
        ),
        migrations.AlterField(
            model_name='test',
            name='test_duration_mins',
            field=models.IntegerField(default=0),
        ),
    ]
