# Generated by Django 2.0.3 on 2018-04-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20180403_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test_sectionsid',
            new_name='test_sectionid',
        ),
    ]
