# Generated by Django 2.1.dev20180322075356 on 2018-04-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20180403_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsection',
            name='section_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
