# Generated by Django 2.1.dev20180322075356 on 2018-04-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_testsection_section_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testsection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
