# Generated by Django 2.1.dev20180322075356 on 2018-04-09 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0005_auto_20180409_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complexity',
            fields=[
                ('complex_id', models.AutoField(primary_key=True, serialize=False)),
                ('complex_description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=1000)),
                ('question_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Complexity')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('choice_id', models.AutoField(primary_key=True, serialize=False)),
                ('choice_text', models.CharField(max_length=500)),
                ('choice_is_correct', models.BooleanField()),
                ('choice_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('questiontype_id', models.AutoField(primary_key=True, serialize=False)),
                ('questiontype_name', models.CharField(max_length=250)),
                ('questiontype_description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestMapping',
            fields=[
                ('testmap_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='custom_assignedtest',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='role',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='test',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_createdby',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_createdon',
        ),
        migrations.RemoveField(
            model_name='test',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='testsection',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='testsection',
            name='section_createdon',
        ),
        migrations.RemoveField(
            model_name='testsection',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='role',
            name='role_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='testsection',
            name='section_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='testmapping',
            name='testmap_testid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Test'),
        ),
        migrations.AddField(
            model_name='testmapping',
            name='testmap_userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='question_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Testsection'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.QuestionType'),
        ),
        migrations.AddField(
            model_name='complexity',
            name='complex_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Test'),
        ),
    ]
