# Generated by Django 2.0.3 on 2018-04-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_auto_20180409_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionmapping',
            old_name='sectionmap_userid',
            new_name='sectionmap_sectionid',
        ),
    ]
