# Generated by Django 2.1.dev20180322075356 on 2018-04-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_auto_20180410_2013'),
        ('administration', '0012_auto_20180411_1505'),
    ]

    operations = [
    ]
