# Generated by Django 2.1.dev20180322075356 on 2018-04-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_merge_20180418_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test_duration_mins',
            new_name='test_duration',
        ),
    ]
