# Generated by Django 2.1.dev20180322075356 on 2018-04-19 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_auto_20180419_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test_duration',
            new_name='test_duration_mins',
        ),
    ]
