# Generated by Django 2.1.dev20180322075356 on 2018-04-25 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0015_auto_20180419_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempTable',
            fields=[
                ('temptable_id', models.AutoField(primary_key=True, serialize=False)),
                ('temptable_created_date', models.DateTimeField(auto_now_add=True)),
                ('temptable_custom_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('temptable_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Question')),
                ('temptable_section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Testsection')),
                ('temptable_test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Test')),
            ],
        ),
    ]
