# Generated by Django 2.1.dev20180322075356 on 2018-04-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_temptable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temptable',
            old_name='temptable_created_date',
            new_name='temp_created_date',
        ),
        migrations.RenameField(
            model_name='temptable',
            old_name='temptable_id',
            new_name='temp_id',
        ),
        migrations.RenameField(
            model_name='temptable',
            old_name='temptable_question_id',
            new_name='temptable_question',
        ),
        migrations.RenameField(
            model_name='temptable',
            old_name='temptable_section_id',
            new_name='temptable_section',
        ),
        migrations.RenameField(
            model_name='temptable',
            old_name='temptable_test_id',
            new_name='temptable_test',
        ),
        migrations.RenameField(
            model_name='temptable',
            old_name='temptable_custom_userid',
            new_name='temptable_userid',
        ),
    ]
