# Generated by Django 2.1.dev20180322075356 on 2018-04-27 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0017_auto_20180425_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempResponse',
            fields=[
                ('temp_response_id', models.AutoField(primary_key=True, serialize=False)),
                ('temp_response_answer', models.CharField(max_length=500)),
                ('temp_response_created_date', models.DateTimeField(auto_now_add=True)),
                ('temp_response_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Question')),
                ('temp_response_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
