# Generated by Django 2.1.dev20180322075356 on 2018-05-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0019_auto_20180504_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmapping',
            name='testmap_complete',
            field=models.BooleanField(default=True),
        ),
    ]
